services:
  userdb:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    networks:
      - krubapigateway_lan
    env_file:
      - ".env"  
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # ports:
    #   # <Port exposed> : < MySQL Port running inside container>
    #   - '3306:3306'
    # expose:
    #   # Opens port 3306 on the container
    #   - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
  userservice:
    build: ./
    container_name: BidKrubUserService
    env_file:
      - ".env"  
    environment:
      PORT: ${SERVICE_PORT}
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
      - '50051:50051'
    expose:
      - ${SERVICE_PORT}
      - '50051'
    networks:
      - krubapigateway_lan
    restart: "unless-stopped"


volumes:
  my-db:

networks:
  krubapigateway_lan:
    external: true
